/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package battleship;

/**
 *
 * @author Luis Oliva
 */

public class GUI extends javax.swing.JFrame {

    public void setNave ()
    {
        
    }
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        f7 = new java.awt.Panel();
        f8 = new java.awt.Panel();
        f1 = new java.awt.Panel();
        f2 = new java.awt.Panel();
        f3 = new java.awt.Panel();
        g4 = new java.awt.Panel();
        g5 = new java.awt.Panel();
        g6 = new java.awt.Panel();
        g7 = new java.awt.Panel();
        g8 = new java.awt.Panel();
        a1 = new java.awt.Panel();
        a2 = new java.awt.Panel();
        a3 = new java.awt.Panel();
        a4 = new java.awt.Panel();
        a5 = new java.awt.Panel();
        a6 = new java.awt.Panel();
        a7 = new java.awt.Panel();
        a8 = new java.awt.Panel();
        b4 = new java.awt.Panel();
        b5 = new java.awt.Panel();
        b6 = new java.awt.Panel();
        b7 = new java.awt.Panel();
        b8 = new java.awt.Panel();
        b1 = new java.awt.Panel();
        b2 = new java.awt.Panel();
        b3 = new java.awt.Panel();
        c4 = new java.awt.Panel();
        c5 = new java.awt.Panel();
        c6 = new java.awt.Panel();
        c7 = new java.awt.Panel();
        c8 = new java.awt.Panel();
        g1 = new java.awt.Panel();
        c1 = new java.awt.Panel();
        g2 = new java.awt.Panel();
        c2 = new java.awt.Panel();
        g3 = new java.awt.Panel();
        h4 = new java.awt.Panel();
        h5 = new java.awt.Panel();
        h6 = new java.awt.Panel();
        h7 = new java.awt.Panel();
        h8 = new java.awt.Panel();
        h1 = new java.awt.Panel();
        h2 = new java.awt.Panel();
        c3 = new java.awt.Panel();
        d4 = new java.awt.Panel();
        d5 = new java.awt.Panel();
        d6 = new java.awt.Panel();
        d7 = new java.awt.Panel();
        d8 = new java.awt.Panel();
        d1 = new java.awt.Panel();
        d2 = new java.awt.Panel();
        h3 = new java.awt.Panel();
        d3 = new java.awt.Panel();
        label10 = new java.awt.Label();
        e4 = new java.awt.Panel();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        e5 = new java.awt.Panel();
        e6 = new java.awt.Panel();
        e7 = new java.awt.Panel();
        e8 = new java.awt.Panel();
        e1 = new java.awt.Panel();
        e2 = new java.awt.Panel();
        e3 = new java.awt.Panel();
        f4 = new java.awt.Panel();
        label17 = new java.awt.Label();
        f5 = new java.awt.Panel();
        f6 = new java.awt.Panel();
        label18 = new java.awt.Label();
        G6 = new java.awt.Panel();
        G7 = new java.awt.Panel();
        G8 = new java.awt.Panel();
        A1 = new java.awt.Panel();
        A2 = new java.awt.Panel();
        A3 = new java.awt.Panel();
        A4 = new java.awt.Panel();
        A5 = new java.awt.Panel();
        A6 = new java.awt.Panel();
        A7 = new java.awt.Panel();
        A8 = new java.awt.Panel();
        B4 = new java.awt.Panel();
        B5 = new java.awt.Panel();
        B6 = new java.awt.Panel();
        B7 = new java.awt.Panel();
        B8 = new java.awt.Panel();
        B1 = new java.awt.Panel();
        B2 = new java.awt.Panel();
        B3 = new java.awt.Panel();
        C4 = new java.awt.Panel();
        C5 = new java.awt.Panel();
        C6 = new java.awt.Panel();
        C7 = new java.awt.Panel();
        C8 = new java.awt.Panel();
        G1 = new java.awt.Panel();
        C1 = new java.awt.Panel();
        G2 = new java.awt.Panel();
        C2 = new java.awt.Panel();
        G3 = new java.awt.Panel();
        H4 = new java.awt.Panel();
        H5 = new java.awt.Panel();
        H6 = new java.awt.Panel();
        H7 = new java.awt.Panel();
        H8 = new java.awt.Panel();
        H1 = new java.awt.Panel();
        H2 = new java.awt.Panel();
        C3 = new java.awt.Panel();
        D4 = new java.awt.Panel();
        D5 = new java.awt.Panel();
        D6 = new java.awt.Panel();
        D7 = new java.awt.Panel();
        D8 = new java.awt.Panel();
        D1 = new java.awt.Panel();
        D2 = new java.awt.Panel();
        H3 = new java.awt.Panel();
        D3 = new java.awt.Panel();
        label19 = new java.awt.Label();
        E4 = new java.awt.Panel();
        label20 = new java.awt.Label();
        label21 = new java.awt.Label();
        label22 = new java.awt.Label();
        label23 = new java.awt.Label();
        label24 = new java.awt.Label();
        label25 = new java.awt.Label();
        E5 = new java.awt.Panel();
        E6 = new java.awt.Panel();
        E7 = new java.awt.Panel();
        E8 = new java.awt.Panel();
        E1 = new java.awt.Panel();
        E2 = new java.awt.Panel();
        E3 = new java.awt.Panel();
        F4 = new java.awt.Panel();
        label26 = new java.awt.Label();
        F5 = new java.awt.Panel();
        F6 = new java.awt.Panel();
        label27 = new java.awt.Label();
        F7 = new java.awt.Panel();
        F8 = new java.awt.Panel();
        F1 = new java.awt.Panel();
        F2 = new java.awt.Panel();
        F3 = new java.awt.Panel();
        G4 = new java.awt.Panel();
        G5 = new java.awt.Panel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        f7.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout f7Layout = new javax.swing.GroupLayout(f7);
        f7.setLayout(f7Layout);
        f7Layout.setHorizontalGroup(
            f7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        f7Layout.setVerticalGroup(
            f7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(f7, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 216, -1, -1));

        f8.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout f8Layout = new javax.swing.GroupLayout(f8);
        f8.setLayout(f8Layout);
        f8Layout.setHorizontalGroup(
            f8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        f8Layout.setVerticalGroup(
            f8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(f8, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 243, -1, -1));

        f1.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout f1Layout = new javax.swing.GroupLayout(f1);
        f1.setLayout(f1Layout);
        f1Layout.setHorizontalGroup(
            f1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        f1Layout.setVerticalGroup(
            f1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 54, -1, -1));

        f2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout f2Layout = new javax.swing.GroupLayout(f2);
        f2.setLayout(f2Layout);
        f2Layout.setHorizontalGroup(
            f2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        f2Layout.setVerticalGroup(
            f2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 81, -1, -1));

        f3.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout f3Layout = new javax.swing.GroupLayout(f3);
        f3.setLayout(f3Layout);
        f3Layout.setHorizontalGroup(
            f3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        f3Layout.setVerticalGroup(
            f3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(f3, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 108, -1, -1));

        g4.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout g4Layout = new javax.swing.GroupLayout(g4);
        g4.setLayout(g4Layout);
        g4Layout.setHorizontalGroup(
            g4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        g4Layout.setVerticalGroup(
            g4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(g4, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 135, -1, -1));

        g5.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout g5Layout = new javax.swing.GroupLayout(g5);
        g5.setLayout(g5Layout);
        g5Layout.setHorizontalGroup(
            g5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        g5Layout.setVerticalGroup(
            g5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(g5, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 162, -1, -1));

        g6.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout g6Layout = new javax.swing.GroupLayout(g6);
        g6.setLayout(g6Layout);
        g6Layout.setHorizontalGroup(
            g6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        g6Layout.setVerticalGroup(
            g6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(g6, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 189, -1, -1));

        g7.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout g7Layout = new javax.swing.GroupLayout(g7);
        g7.setLayout(g7Layout);
        g7Layout.setHorizontalGroup(
            g7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        g7Layout.setVerticalGroup(
            g7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(g7, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 216, -1, -1));

        g8.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout g8Layout = new javax.swing.GroupLayout(g8);
        g8.setLayout(g8Layout);
        g8Layout.setHorizontalGroup(
            g8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        g8Layout.setVerticalGroup(
            g8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(g8, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 243, -1, -1));

        a1.setBackground(new java.awt.Color(0, 102, 102));
        a1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout a1Layout = new javax.swing.GroupLayout(a1);
        a1.setLayout(a1Layout);
        a1Layout.setHorizontalGroup(
            a1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        a1Layout.setVerticalGroup(
            a1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 54, -1, -1));

        a2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout a2Layout = new javax.swing.GroupLayout(a2);
        a2.setLayout(a2Layout);
        a2Layout.setHorizontalGroup(
            a2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        a2Layout.setVerticalGroup(
            a2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 81, -1, -1));

        a3.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout a3Layout = new javax.swing.GroupLayout(a3);
        a3.setLayout(a3Layout);
        a3Layout.setHorizontalGroup(
            a3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        a3Layout.setVerticalGroup(
            a3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 108, -1, -1));

        a4.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout a4Layout = new javax.swing.GroupLayout(a4);
        a4.setLayout(a4Layout);
        a4Layout.setHorizontalGroup(
            a4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        a4Layout.setVerticalGroup(
            a4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 135, -1, -1));

        a5.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout a5Layout = new javax.swing.GroupLayout(a5);
        a5.setLayout(a5Layout);
        a5Layout.setHorizontalGroup(
            a5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        a5Layout.setVerticalGroup(
            a5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 162, -1, -1));

        a6.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout a6Layout = new javax.swing.GroupLayout(a6);
        a6.setLayout(a6Layout);
        a6Layout.setHorizontalGroup(
            a6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        a6Layout.setVerticalGroup(
            a6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 189, -1, -1));

        a7.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout a7Layout = new javax.swing.GroupLayout(a7);
        a7.setLayout(a7Layout);
        a7Layout.setHorizontalGroup(
            a7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        a7Layout.setVerticalGroup(
            a7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(a7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 216, -1, -1));

        a8.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout a8Layout = new javax.swing.GroupLayout(a8);
        a8.setLayout(a8Layout);
        a8Layout.setHorizontalGroup(
            a8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        a8Layout.setVerticalGroup(
            a8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(a8, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 243, -1, -1));

        b4.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout b4Layout = new javax.swing.GroupLayout(b4);
        b4.setLayout(b4Layout);
        b4Layout.setHorizontalGroup(
            b4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        b4Layout.setVerticalGroup(
            b4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 135, -1, -1));

        b5.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout b5Layout = new javax.swing.GroupLayout(b5);
        b5.setLayout(b5Layout);
        b5Layout.setHorizontalGroup(
            b5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        b5Layout.setVerticalGroup(
            b5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 162, -1, -1));

        b6.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout b6Layout = new javax.swing.GroupLayout(b6);
        b6.setLayout(b6Layout);
        b6Layout.setHorizontalGroup(
            b6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        b6Layout.setVerticalGroup(
            b6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 189, -1, -1));

        b7.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout b7Layout = new javax.swing.GroupLayout(b7);
        b7.setLayout(b7Layout);
        b7Layout.setHorizontalGroup(
            b7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        b7Layout.setVerticalGroup(
            b7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 216, -1, -1));

        b8.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout b8Layout = new javax.swing.GroupLayout(b8);
        b8.setLayout(b8Layout);
        b8Layout.setHorizontalGroup(
            b8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        b8Layout.setVerticalGroup(
            b8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 243, -1, -1));

        b1.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout b1Layout = new javax.swing.GroupLayout(b1);
        b1.setLayout(b1Layout);
        b1Layout.setHorizontalGroup(
            b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        b1Layout.setVerticalGroup(
            b1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 54, -1, -1));

        b2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout b2Layout = new javax.swing.GroupLayout(b2);
        b2.setLayout(b2Layout);
        b2Layout.setHorizontalGroup(
            b2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        b2Layout.setVerticalGroup(
            b2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 81, -1, -1));

        b3.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout b3Layout = new javax.swing.GroupLayout(b3);
        b3.setLayout(b3Layout);
        b3Layout.setHorizontalGroup(
            b3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        b3Layout.setVerticalGroup(
            b3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 108, -1, -1));

        c4.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout c4Layout = new javax.swing.GroupLayout(c4);
        c4.setLayout(c4Layout);
        c4Layout.setHorizontalGroup(
            c4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        c4Layout.setVerticalGroup(
            c4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 135, -1, -1));

        c5.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout c5Layout = new javax.swing.GroupLayout(c5);
        c5.setLayout(c5Layout);
        c5Layout.setHorizontalGroup(
            c5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        c5Layout.setVerticalGroup(
            c5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 162, -1, -1));

        c6.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout c6Layout = new javax.swing.GroupLayout(c6);
        c6.setLayout(c6Layout);
        c6Layout.setHorizontalGroup(
            c6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        c6Layout.setVerticalGroup(
            c6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 189, -1, -1));

        c7.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout c7Layout = new javax.swing.GroupLayout(c7);
        c7.setLayout(c7Layout);
        c7Layout.setHorizontalGroup(
            c7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        c7Layout.setVerticalGroup(
            c7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 216, -1, -1));

        c8.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout c8Layout = new javax.swing.GroupLayout(c8);
        c8.setLayout(c8Layout);
        c8Layout.setHorizontalGroup(
            c8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        c8Layout.setVerticalGroup(
            c8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 243, -1, -1));

        g1.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout g1Layout = new javax.swing.GroupLayout(g1);
        g1.setLayout(g1Layout);
        g1Layout.setHorizontalGroup(
            g1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        g1Layout.setVerticalGroup(
            g1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(g1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 54, -1, -1));

        c1.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout c1Layout = new javax.swing.GroupLayout(c1);
        c1.setLayout(c1Layout);
        c1Layout.setHorizontalGroup(
            c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        c1Layout.setVerticalGroup(
            c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 54, -1, -1));

        g2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout g2Layout = new javax.swing.GroupLayout(g2);
        g2.setLayout(g2Layout);
        g2Layout.setHorizontalGroup(
            g2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        g2Layout.setVerticalGroup(
            g2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(g2, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 81, -1, -1));

        c2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout c2Layout = new javax.swing.GroupLayout(c2);
        c2.setLayout(c2Layout);
        c2Layout.setHorizontalGroup(
            c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        c2Layout.setVerticalGroup(
            c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 81, -1, -1));

        g3.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout g3Layout = new javax.swing.GroupLayout(g3);
        g3.setLayout(g3Layout);
        g3Layout.setHorizontalGroup(
            g3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        g3Layout.setVerticalGroup(
            g3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(g3, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 108, -1, -1));

        h4.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout h4Layout = new javax.swing.GroupLayout(h4);
        h4.setLayout(h4Layout);
        h4Layout.setHorizontalGroup(
            h4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        h4Layout.setVerticalGroup(
            h4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(h4, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 135, -1, -1));

        h5.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout h5Layout = new javax.swing.GroupLayout(h5);
        h5.setLayout(h5Layout);
        h5Layout.setHorizontalGroup(
            h5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        h5Layout.setVerticalGroup(
            h5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(h5, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 162, -1, -1));

        h6.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout h6Layout = new javax.swing.GroupLayout(h6);
        h6.setLayout(h6Layout);
        h6Layout.setHorizontalGroup(
            h6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        h6Layout.setVerticalGroup(
            h6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(h6, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 189, -1, -1));

        h7.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout h7Layout = new javax.swing.GroupLayout(h7);
        h7.setLayout(h7Layout);
        h7Layout.setHorizontalGroup(
            h7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        h7Layout.setVerticalGroup(
            h7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(h7, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 216, -1, -1));

        h8.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout h8Layout = new javax.swing.GroupLayout(h8);
        h8.setLayout(h8Layout);
        h8Layout.setHorizontalGroup(
            h8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        h8Layout.setVerticalGroup(
            h8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(h8, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 243, -1, -1));

        h1.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout h1Layout = new javax.swing.GroupLayout(h1);
        h1.setLayout(h1Layout);
        h1Layout.setHorizontalGroup(
            h1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        h1Layout.setVerticalGroup(
            h1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(h1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 54, -1, -1));

        h2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout h2Layout = new javax.swing.GroupLayout(h2);
        h2.setLayout(h2Layout);
        h2Layout.setHorizontalGroup(
            h2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        h2Layout.setVerticalGroup(
            h2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(h2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 81, -1, -1));

        c3.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout c3Layout = new javax.swing.GroupLayout(c3);
        c3.setLayout(c3Layout);
        c3Layout.setHorizontalGroup(
            c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        c3Layout.setVerticalGroup(
            c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 108, -1, -1));

        d4.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout d4Layout = new javax.swing.GroupLayout(d4);
        d4.setLayout(d4Layout);
        d4Layout.setHorizontalGroup(
            d4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        d4Layout.setVerticalGroup(
            d4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(d4, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 135, -1, -1));

        d5.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout d5Layout = new javax.swing.GroupLayout(d5);
        d5.setLayout(d5Layout);
        d5Layout.setHorizontalGroup(
            d5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        d5Layout.setVerticalGroup(
            d5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(d5, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 162, -1, -1));

        d6.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout d6Layout = new javax.swing.GroupLayout(d6);
        d6.setLayout(d6Layout);
        d6Layout.setHorizontalGroup(
            d6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        d6Layout.setVerticalGroup(
            d6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(d6, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 189, -1, -1));

        d7.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout d7Layout = new javax.swing.GroupLayout(d7);
        d7.setLayout(d7Layout);
        d7Layout.setHorizontalGroup(
            d7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        d7Layout.setVerticalGroup(
            d7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(d7, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 216, -1, -1));

        d8.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout d8Layout = new javax.swing.GroupLayout(d8);
        d8.setLayout(d8Layout);
        d8Layout.setHorizontalGroup(
            d8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        d8Layout.setVerticalGroup(
            d8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(d8, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 243, -1, -1));

        d1.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout d1Layout = new javax.swing.GroupLayout(d1);
        d1.setLayout(d1Layout);
        d1Layout.setHorizontalGroup(
            d1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        d1Layout.setVerticalGroup(
            d1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 54, -1, -1));

        d2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout d2Layout = new javax.swing.GroupLayout(d2);
        d2.setLayout(d2Layout);
        d2Layout.setHorizontalGroup(
            d2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        d2Layout.setVerticalGroup(
            d2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 81, -1, -1));

        h3.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout h3Layout = new javax.swing.GroupLayout(h3);
        h3.setLayout(h3Layout);
        h3Layout.setHorizontalGroup(
            h3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        h3Layout.setVerticalGroup(
            h3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(h3, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 108, -1, -1));

        d3.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout d3Layout = new javax.swing.GroupLayout(d3);
        d3.setLayout(d3Layout);
        d3Layout.setHorizontalGroup(
            d3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        d3Layout.setVerticalGroup(
            d3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(d3, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 108, -1, -1));

        label10.setText("A       B      C      D      E      F      G      H ");
        getContentPane().add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 32, 214, -1));

        e4.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout e4Layout = new javax.swing.GroupLayout(e4);
        e4.setLayout(e4Layout);
        e4Layout.setHorizontalGroup(
            e4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        e4Layout.setVerticalGroup(
            e4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(e4, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 135, -1, -1));

        label11.setName(""); // NOI18N
        label11.setText("2");
        getContentPane().add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 86, -1, -1));

        label12.setName(""); // NOI18N
        label12.setText("1");
        getContentPane().add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, -1, -1));

        label13.setName(""); // NOI18N
        label13.setText("3");
        getContentPane().add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 116, -1, 12));

        label14.setName(""); // NOI18N
        label14.setText("4");
        getContentPane().add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        label15.setName(""); // NOI18N
        label15.setText("5");
        getContentPane().add(label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 12));

        label16.setName(""); // NOI18N
        label16.setText("6");
        getContentPane().add(label16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 194, -1, -1));

        e5.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout e5Layout = new javax.swing.GroupLayout(e5);
        e5.setLayout(e5Layout);
        e5Layout.setHorizontalGroup(
            e5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        e5Layout.setVerticalGroup(
            e5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(e5, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 162, -1, -1));

        e6.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout e6Layout = new javax.swing.GroupLayout(e6);
        e6.setLayout(e6Layout);
        e6Layout.setHorizontalGroup(
            e6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        e6Layout.setVerticalGroup(
            e6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(e6, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 189, -1, -1));

        e7.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout e7Layout = new javax.swing.GroupLayout(e7);
        e7.setLayout(e7Layout);
        e7Layout.setHorizontalGroup(
            e7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        e7Layout.setVerticalGroup(
            e7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(e7, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 216, -1, -1));

        e8.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout e8Layout = new javax.swing.GroupLayout(e8);
        e8.setLayout(e8Layout);
        e8Layout.setHorizontalGroup(
            e8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        e8Layout.setVerticalGroup(
            e8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(e8, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 243, -1, -1));

        e1.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout e1Layout = new javax.swing.GroupLayout(e1);
        e1.setLayout(e1Layout);
        e1Layout.setHorizontalGroup(
            e1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        e1Layout.setVerticalGroup(
            e1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 54, -1, -1));

        e2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout e2Layout = new javax.swing.GroupLayout(e2);
        e2.setLayout(e2Layout);
        e2Layout.setHorizontalGroup(
            e2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        e2Layout.setVerticalGroup(
            e2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 81, -1, -1));

        e3.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout e3Layout = new javax.swing.GroupLayout(e3);
        e3.setLayout(e3Layout);
        e3Layout.setHorizontalGroup(
            e3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        e3Layout.setVerticalGroup(
            e3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(e3, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 108, -1, -1));

        f4.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout f4Layout = new javax.swing.GroupLayout(f4);
        f4.setLayout(f4Layout);
        f4Layout.setHorizontalGroup(
            f4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        f4Layout.setVerticalGroup(
            f4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(f4, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 135, -1, -1));

        label17.setName(""); // NOI18N
        label17.setText("7");
        getContentPane().add(label17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 221, -1, -1));

        f5.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout f5Layout = new javax.swing.GroupLayout(f5);
        f5.setLayout(f5Layout);
        f5Layout.setHorizontalGroup(
            f5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        f5Layout.setVerticalGroup(
            f5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(f5, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 162, -1, -1));

        f6.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout f6Layout = new javax.swing.GroupLayout(f6);
        f6.setLayout(f6Layout);
        f6Layout.setHorizontalGroup(
            f6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        f6Layout.setVerticalGroup(
            f6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(f6, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 189, -1, -1));

        label18.setName(""); // NOI18N
        label18.setText("8");
        getContentPane().add(label18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 243, -1, -1));

        G6.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout G6Layout = new javax.swing.GroupLayout(G6);
        G6.setLayout(G6Layout);
        G6Layout.setHorizontalGroup(
            G6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        G6Layout.setVerticalGroup(
            G6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(G6, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 189, -1, -1));

        G7.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout G7Layout = new javax.swing.GroupLayout(G7);
        G7.setLayout(G7Layout);
        G7Layout.setHorizontalGroup(
            G7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        G7Layout.setVerticalGroup(
            G7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(G7, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 216, -1, -1));

        G8.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout G8Layout = new javax.swing.GroupLayout(G8);
        G8.setLayout(G8Layout);
        G8Layout.setHorizontalGroup(
            G8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        G8Layout.setVerticalGroup(
            G8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(G8, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 243, -1, -1));

        A1.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout A1Layout = new javax.swing.GroupLayout(A1);
        A1.setLayout(A1Layout);
        A1Layout.setHorizontalGroup(
            A1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        A1Layout.setVerticalGroup(
            A1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 54, -1, -1));

        A2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout A2Layout = new javax.swing.GroupLayout(A2);
        A2.setLayout(A2Layout);
        A2Layout.setHorizontalGroup(
            A2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        A2Layout.setVerticalGroup(
            A2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 81, -1, -1));

        A3.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout A3Layout = new javax.swing.GroupLayout(A3);
        A3.setLayout(A3Layout);
        A3Layout.setHorizontalGroup(
            A3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        A3Layout.setVerticalGroup(
            A3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 108, -1, -1));

        A4.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout A4Layout = new javax.swing.GroupLayout(A4);
        A4.setLayout(A4Layout);
        A4Layout.setHorizontalGroup(
            A4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        A4Layout.setVerticalGroup(
            A4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 135, -1, -1));

        A5.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout A5Layout = new javax.swing.GroupLayout(A5);
        A5.setLayout(A5Layout);
        A5Layout.setHorizontalGroup(
            A5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        A5Layout.setVerticalGroup(
            A5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(A5, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 162, -1, -1));

        A6.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout A6Layout = new javax.swing.GroupLayout(A6);
        A6.setLayout(A6Layout);
        A6Layout.setHorizontalGroup(
            A6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        A6Layout.setVerticalGroup(
            A6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(A6, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 189, -1, -1));

        A7.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout A7Layout = new javax.swing.GroupLayout(A7);
        A7.setLayout(A7Layout);
        A7Layout.setHorizontalGroup(
            A7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        A7Layout.setVerticalGroup(
            A7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(A7, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 216, -1, -1));

        A8.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout A8Layout = new javax.swing.GroupLayout(A8);
        A8.setLayout(A8Layout);
        A8Layout.setHorizontalGroup(
            A8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        A8Layout.setVerticalGroup(
            A8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(A8, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 243, -1, -1));

        B4.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout B4Layout = new javax.swing.GroupLayout(B4);
        B4.setLayout(B4Layout);
        B4Layout.setHorizontalGroup(
            B4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        B4Layout.setVerticalGroup(
            B4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 135, -1, -1));

        B5.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout B5Layout = new javax.swing.GroupLayout(B5);
        B5.setLayout(B5Layout);
        B5Layout.setHorizontalGroup(
            B5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        B5Layout.setVerticalGroup(
            B5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 162, -1, -1));

        B6.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout B6Layout = new javax.swing.GroupLayout(B6);
        B6.setLayout(B6Layout);
        B6Layout.setHorizontalGroup(
            B6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        B6Layout.setVerticalGroup(
            B6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 189, -1, -1));

        B7.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout B7Layout = new javax.swing.GroupLayout(B7);
        B7.setLayout(B7Layout);
        B7Layout.setHorizontalGroup(
            B7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        B7Layout.setVerticalGroup(
            B7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(B7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 216, -1, -1));

        B8.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout B8Layout = new javax.swing.GroupLayout(B8);
        B8.setLayout(B8Layout);
        B8Layout.setHorizontalGroup(
            B8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        B8Layout.setVerticalGroup(
            B8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(B8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 243, -1, -1));

        B1.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout B1Layout = new javax.swing.GroupLayout(B1);
        B1.setLayout(B1Layout);
        B1Layout.setHorizontalGroup(
            B1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        B1Layout.setVerticalGroup(
            B1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 54, -1, -1));

        B2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout B2Layout = new javax.swing.GroupLayout(B2);
        B2.setLayout(B2Layout);
        B2Layout.setHorizontalGroup(
            B2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        B2Layout.setVerticalGroup(
            B2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 81, -1, -1));

        B3.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout B3Layout = new javax.swing.GroupLayout(B3);
        B3.setLayout(B3Layout);
        B3Layout.setHorizontalGroup(
            B3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        B3Layout.setVerticalGroup(
            B3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 108, -1, -1));

        C4.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout C4Layout = new javax.swing.GroupLayout(C4);
        C4.setLayout(C4Layout);
        C4Layout.setHorizontalGroup(
            C4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        C4Layout.setVerticalGroup(
            C4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 135, -1, -1));

        C5.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout C5Layout = new javax.swing.GroupLayout(C5);
        C5.setLayout(C5Layout);
        C5Layout.setHorizontalGroup(
            C5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        C5Layout.setVerticalGroup(
            C5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 162, -1, -1));

        C6.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout C6Layout = new javax.swing.GroupLayout(C6);
        C6.setLayout(C6Layout);
        C6Layout.setHorizontalGroup(
            C6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        C6Layout.setVerticalGroup(
            C6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(C6, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 189, -1, -1));

        C7.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout C7Layout = new javax.swing.GroupLayout(C7);
        C7.setLayout(C7Layout);
        C7Layout.setHorizontalGroup(
            C7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        C7Layout.setVerticalGroup(
            C7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(C7, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 216, -1, -1));

        C8.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout C8Layout = new javax.swing.GroupLayout(C8);
        C8.setLayout(C8Layout);
        C8Layout.setHorizontalGroup(
            C8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        C8Layout.setVerticalGroup(
            C8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(C8, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 243, -1, -1));

        G1.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout G1Layout = new javax.swing.GroupLayout(G1);
        G1.setLayout(G1Layout);
        G1Layout.setHorizontalGroup(
            G1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        G1Layout.setVerticalGroup(
            G1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(G1, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 54, -1, -1));

        C1.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout C1Layout = new javax.swing.GroupLayout(C1);
        C1.setLayout(C1Layout);
        C1Layout.setHorizontalGroup(
            C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        C1Layout.setVerticalGroup(
            C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 54, -1, -1));

        G2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout G2Layout = new javax.swing.GroupLayout(G2);
        G2.setLayout(G2Layout);
        G2Layout.setHorizontalGroup(
            G2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        G2Layout.setVerticalGroup(
            G2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 81, -1, -1));

        C2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout C2Layout = new javax.swing.GroupLayout(C2);
        C2.setLayout(C2Layout);
        C2Layout.setHorizontalGroup(
            C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        C2Layout.setVerticalGroup(
            C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 81, -1, -1));

        G3.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout G3Layout = new javax.swing.GroupLayout(G3);
        G3.setLayout(G3Layout);
        G3Layout.setHorizontalGroup(
            G3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        G3Layout.setVerticalGroup(
            G3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(G3, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 108, -1, -1));

        H4.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout H4Layout = new javax.swing.GroupLayout(H4);
        H4.setLayout(H4Layout);
        H4Layout.setHorizontalGroup(
            H4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        H4Layout.setVerticalGroup(
            H4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(H4, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 135, -1, -1));

        H5.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout H5Layout = new javax.swing.GroupLayout(H5);
        H5.setLayout(H5Layout);
        H5Layout.setHorizontalGroup(
            H5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        H5Layout.setVerticalGroup(
            H5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(H5, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 162, -1, -1));

        H6.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout H6Layout = new javax.swing.GroupLayout(H6);
        H6.setLayout(H6Layout);
        H6Layout.setHorizontalGroup(
            H6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        H6Layout.setVerticalGroup(
            H6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(H6, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 189, -1, -1));

        H7.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout H7Layout = new javax.swing.GroupLayout(H7);
        H7.setLayout(H7Layout);
        H7Layout.setHorizontalGroup(
            H7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        H7Layout.setVerticalGroup(
            H7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(H7, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 216, -1, -1));

        H8.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout H8Layout = new javax.swing.GroupLayout(H8);
        H8.setLayout(H8Layout);
        H8Layout.setHorizontalGroup(
            H8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        H8Layout.setVerticalGroup(
            H8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(H8, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 243, -1, -1));

        H1.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout H1Layout = new javax.swing.GroupLayout(H1);
        H1.setLayout(H1Layout);
        H1Layout.setHorizontalGroup(
            H1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        H1Layout.setVerticalGroup(
            H1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(H1, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 54, -1, -1));

        H2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout H2Layout = new javax.swing.GroupLayout(H2);
        H2.setLayout(H2Layout);
        H2Layout.setHorizontalGroup(
            H2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        H2Layout.setVerticalGroup(
            H2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(H2, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 81, -1, -1));

        C3.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout C3Layout = new javax.swing.GroupLayout(C3);
        C3.setLayout(C3Layout);
        C3Layout.setHorizontalGroup(
            C3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        C3Layout.setVerticalGroup(
            C3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 108, -1, -1));

        D4.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout D4Layout = new javax.swing.GroupLayout(D4);
        D4.setLayout(D4Layout);
        D4Layout.setHorizontalGroup(
            D4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        D4Layout.setVerticalGroup(
            D4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(D4, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 135, -1, -1));

        D5.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout D5Layout = new javax.swing.GroupLayout(D5);
        D5.setLayout(D5Layout);
        D5Layout.setHorizontalGroup(
            D5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        D5Layout.setVerticalGroup(
            D5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(D5, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 162, -1, -1));

        D6.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout D6Layout = new javax.swing.GroupLayout(D6);
        D6.setLayout(D6Layout);
        D6Layout.setHorizontalGroup(
            D6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        D6Layout.setVerticalGroup(
            D6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(D6, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 189, -1, -1));

        D7.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout D7Layout = new javax.swing.GroupLayout(D7);
        D7.setLayout(D7Layout);
        D7Layout.setHorizontalGroup(
            D7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        D7Layout.setVerticalGroup(
            D7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(D7, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 216, -1, -1));

        D8.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout D8Layout = new javax.swing.GroupLayout(D8);
        D8.setLayout(D8Layout);
        D8Layout.setHorizontalGroup(
            D8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        D8Layout.setVerticalGroup(
            D8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(D8, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 243, -1, -1));

        D1.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout D1Layout = new javax.swing.GroupLayout(D1);
        D1.setLayout(D1Layout);
        D1Layout.setHorizontalGroup(
            D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        D1Layout.setVerticalGroup(
            D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 54, -1, -1));

        D2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout D2Layout = new javax.swing.GroupLayout(D2);
        D2.setLayout(D2Layout);
        D2Layout.setHorizontalGroup(
            D2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        D2Layout.setVerticalGroup(
            D2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 81, -1, -1));

        H3.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout H3Layout = new javax.swing.GroupLayout(H3);
        H3.setLayout(H3Layout);
        H3Layout.setHorizontalGroup(
            H3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        H3Layout.setVerticalGroup(
            H3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(H3, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 108, -1, -1));

        D3.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout D3Layout = new javax.swing.GroupLayout(D3);
        D3.setLayout(D3Layout);
        D3Layout.setHorizontalGroup(
            D3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        D3Layout.setVerticalGroup(
            D3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(D3, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 108, -1, -1));

        label19.setText("A       B      C      D      E      F      G      H ");
        getContentPane().add(label19, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 32, 214, -1));

        E4.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout E4Layout = new javax.swing.GroupLayout(E4);
        E4.setLayout(E4Layout);
        E4Layout.setHorizontalGroup(
            E4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        E4Layout.setVerticalGroup(
            E4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(E4, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 135, -1, -1));

        label20.setName(""); // NOI18N
        label20.setText("2");
        getContentPane().add(label20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 86, -1, -1));

        label21.setName(""); // NOI18N
        label21.setText("1");
        getContentPane().add(label21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 59, -1, -1));

        label22.setName(""); // NOI18N
        label22.setText("3");
        getContentPane().add(label22, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 116, -1, 12));

        label23.setName(""); // NOI18N
        label23.setText("4");
        getContentPane().add(label23, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        label24.setName(""); // NOI18N
        label24.setText("5");
        getContentPane().add(label24, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, 12));

        label25.setName(""); // NOI18N
        label25.setText("6");
        getContentPane().add(label25, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 194, -1, -1));

        E5.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout E5Layout = new javax.swing.GroupLayout(E5);
        E5.setLayout(E5Layout);
        E5Layout.setHorizontalGroup(
            E5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        E5Layout.setVerticalGroup(
            E5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(E5, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 162, -1, -1));

        E6.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout E6Layout = new javax.swing.GroupLayout(E6);
        E6.setLayout(E6Layout);
        E6Layout.setHorizontalGroup(
            E6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        E6Layout.setVerticalGroup(
            E6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(E6, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 189, -1, -1));

        E7.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout E7Layout = new javax.swing.GroupLayout(E7);
        E7.setLayout(E7Layout);
        E7Layout.setHorizontalGroup(
            E7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        E7Layout.setVerticalGroup(
            E7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(E7, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 216, -1, -1));

        E8.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout E8Layout = new javax.swing.GroupLayout(E8);
        E8.setLayout(E8Layout);
        E8Layout.setHorizontalGroup(
            E8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        E8Layout.setVerticalGroup(
            E8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(E8, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 243, -1, -1));

        E1.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout E1Layout = new javax.swing.GroupLayout(E1);
        E1.setLayout(E1Layout);
        E1Layout.setHorizontalGroup(
            E1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        E1Layout.setVerticalGroup(
            E1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 54, -1, -1));

        E2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout E2Layout = new javax.swing.GroupLayout(E2);
        E2.setLayout(E2Layout);
        E2Layout.setHorizontalGroup(
            E2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        E2Layout.setVerticalGroup(
            E2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(E2, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 81, -1, -1));

        E3.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout E3Layout = new javax.swing.GroupLayout(E3);
        E3.setLayout(E3Layout);
        E3Layout.setHorizontalGroup(
            E3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        E3Layout.setVerticalGroup(
            E3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(E3, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 108, -1, -1));

        F4.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout F4Layout = new javax.swing.GroupLayout(F4);
        F4.setLayout(F4Layout);
        F4Layout.setHorizontalGroup(
            F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        F4Layout.setVerticalGroup(
            F4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(F4, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 135, -1, -1));

        label26.setName(""); // NOI18N
        label26.setText("7");
        getContentPane().add(label26, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 221, -1, -1));

        F5.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout F5Layout = new javax.swing.GroupLayout(F5);
        F5.setLayout(F5Layout);
        F5Layout.setHorizontalGroup(
            F5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        F5Layout.setVerticalGroup(
            F5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(F5, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 162, -1, -1));

        F6.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout F6Layout = new javax.swing.GroupLayout(F6);
        F6.setLayout(F6Layout);
        F6Layout.setHorizontalGroup(
            F6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        F6Layout.setVerticalGroup(
            F6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(F6, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 189, -1, -1));

        label27.setName(""); // NOI18N
        label27.setText("8");
        getContentPane().add(label27, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 243, -1, -1));

        F7.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout F7Layout = new javax.swing.GroupLayout(F7);
        F7.setLayout(F7Layout);
        F7Layout.setHorizontalGroup(
            F7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        F7Layout.setVerticalGroup(
            F7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(F7, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 216, -1, -1));

        F8.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout F8Layout = new javax.swing.GroupLayout(F8);
        F8.setLayout(F8Layout);
        F8Layout.setHorizontalGroup(
            F8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        F8Layout.setVerticalGroup(
            F8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(F8, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 243, -1, -1));

        F1.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout F1Layout = new javax.swing.GroupLayout(F1);
        F1.setLayout(F1Layout);
        F1Layout.setHorizontalGroup(
            F1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        F1Layout.setVerticalGroup(
            F1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 54, -1, -1));

        F2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout F2Layout = new javax.swing.GroupLayout(F2);
        F2.setLayout(F2Layout);
        F2Layout.setHorizontalGroup(
            F2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        F2Layout.setVerticalGroup(
            F2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 81, -1, -1));

        F3.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout F3Layout = new javax.swing.GroupLayout(F3);
        F3.setLayout(F3Layout);
        F3Layout.setHorizontalGroup(
            F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        F3Layout.setVerticalGroup(
            F3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 108, -1, -1));

        G4.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout G4Layout = new javax.swing.GroupLayout(G4);
        G4.setLayout(G4Layout);
        G4Layout.setHorizontalGroup(
            G4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        G4Layout.setVerticalGroup(
            G4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(G4, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 135, -1, -1));

        G5.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout G5Layout = new javax.swing.GroupLayout(G5);
        G5.setLayout(G5Layout);
        G5Layout.setHorizontalGroup(
            G5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        G5Layout.setVerticalGroup(
            G5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(G5, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 162, -1, -1));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(899, 399));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void a1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1MouseClicked
        // TODO add your handling code here:
   
    }//GEN-LAST:event_a1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel A1;
    private java.awt.Panel A2;
    private java.awt.Panel A3;
    private java.awt.Panel A4;
    private java.awt.Panel A5;
    private java.awt.Panel A6;
    private java.awt.Panel A7;
    private java.awt.Panel A8;
    private java.awt.Panel B1;
    private java.awt.Panel B2;
    private java.awt.Panel B3;
    private java.awt.Panel B4;
    private java.awt.Panel B5;
    private java.awt.Panel B6;
    private java.awt.Panel B7;
    private java.awt.Panel B8;
    private java.awt.Panel C1;
    private java.awt.Panel C2;
    private java.awt.Panel C3;
    private java.awt.Panel C4;
    private java.awt.Panel C5;
    private java.awt.Panel C6;
    private java.awt.Panel C7;
    private java.awt.Panel C8;
    private java.awt.Panel D1;
    private java.awt.Panel D2;
    private java.awt.Panel D3;
    private java.awt.Panel D4;
    private java.awt.Panel D5;
    private java.awt.Panel D6;
    private java.awt.Panel D7;
    private java.awt.Panel D8;
    private java.awt.Panel E1;
    private java.awt.Panel E2;
    private java.awt.Panel E3;
    private java.awt.Panel E4;
    private java.awt.Panel E5;
    private java.awt.Panel E6;
    private java.awt.Panel E7;
    private java.awt.Panel E8;
    private java.awt.Panel F1;
    private java.awt.Panel F2;
    private java.awt.Panel F3;
    private java.awt.Panel F4;
    private java.awt.Panel F5;
    private java.awt.Panel F6;
    private java.awt.Panel F7;
    private java.awt.Panel F8;
    private java.awt.Panel G1;
    private java.awt.Panel G2;
    private java.awt.Panel G3;
    private java.awt.Panel G4;
    private java.awt.Panel G5;
    private java.awt.Panel G6;
    private java.awt.Panel G7;
    private java.awt.Panel G8;
    private java.awt.Panel H1;
    private java.awt.Panel H2;
    private java.awt.Panel H3;
    private java.awt.Panel H4;
    private java.awt.Panel H5;
    private java.awt.Panel H6;
    private java.awt.Panel H7;
    private java.awt.Panel H8;
    private java.awt.Panel a1;
    private java.awt.Panel a2;
    private java.awt.Panel a3;
    private java.awt.Panel a4;
    private java.awt.Panel a5;
    private java.awt.Panel a6;
    private java.awt.Panel a7;
    private java.awt.Panel a8;
    private java.awt.Panel b1;
    private java.awt.Panel b2;
    private java.awt.Panel b3;
    private java.awt.Panel b4;
    private java.awt.Panel b5;
    private java.awt.Panel b6;
    private java.awt.Panel b7;
    private java.awt.Panel b8;
    private java.awt.Panel c1;
    private java.awt.Panel c2;
    private java.awt.Panel c3;
    private java.awt.Panel c4;
    private java.awt.Panel c5;
    private java.awt.Panel c6;
    private java.awt.Panel c7;
    private java.awt.Panel c8;
    private java.awt.Panel d1;
    private java.awt.Panel d2;
    private java.awt.Panel d3;
    private java.awt.Panel d4;
    private java.awt.Panel d5;
    private java.awt.Panel d6;
    private java.awt.Panel d7;
    private java.awt.Panel d8;
    private java.awt.Panel e1;
    private java.awt.Panel e2;
    private java.awt.Panel e3;
    private java.awt.Panel e4;
    private java.awt.Panel e5;
    private java.awt.Panel e6;
    private java.awt.Panel e7;
    private java.awt.Panel e8;
    private java.awt.Panel f1;
    private java.awt.Panel f2;
    private java.awt.Panel f3;
    private java.awt.Panel f4;
    private java.awt.Panel f5;
    private java.awt.Panel f6;
    private java.awt.Panel f7;
    private java.awt.Panel f8;
    private java.awt.Panel g1;
    private java.awt.Panel g2;
    private java.awt.Panel g3;
    private java.awt.Panel g4;
    private java.awt.Panel g5;
    private java.awt.Panel g6;
    private java.awt.Panel g7;
    private java.awt.Panel g8;
    private java.awt.Panel h1;
    private java.awt.Panel h2;
    private java.awt.Panel h3;
    private java.awt.Panel h4;
    private java.awt.Panel h5;
    private java.awt.Panel h6;
    private java.awt.Panel h7;
    private java.awt.Panel h8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label20;
    private java.awt.Label label21;
    private java.awt.Label label22;
    private java.awt.Label label23;
    private java.awt.Label label24;
    private java.awt.Label label25;
    private java.awt.Label label26;
    private java.awt.Label label27;
    // End of variables declaration//GEN-END:variables
}
